# Meta data
title: 'Burger Art'
author: 'Timon Riemslagh'
description: ''

# Site navigation
navigation:
  - title: home
    url: index/
  - title: grid
    url: grid/

# Exclude these files from the build process
exclude: ['_site','scss','*scss','Gem*','Guard*','*rb','.sass-cache','.git*','config.rb','*.md','*.json','docroot','node_modules','gulpfile.js','install.sh','lint.yml']
